# app.yaml
runtime: python39
handlers:
- url: /.*
  script: auto
  
entrypoint: gunicorn -b :$PORT main:app 

env_variables:
  GCLOUD_STORAGE_BUCKET: cancer_treatment
  GOOGLE_CLOUD_PROJECT: glowing-program-379304
